#macro LEXICON_USE_CACHE true
#macro LEXICON_USE_ADVANCE_CACHE true
#macro LEXICON_AUTO_GC_CACHE true
#macro LEXICON_GC_NEXT_TICK 60
#macro LEXICON_DEBUG_WARNINGS false
#macro LEXICON_CACHE_TIMEOUT 4000