enum lexicon_date_format {
	YEAR_MONTH_DAY_DASHES,
	MONTH_DAY_YEAR_DASHES,
	DAY_MONTH_YEAR_DASHES,
	YEAR_MONTH_DAY_SLASHES,
	MONTH_DAY_YEAR_SLASHES,
	DAY_MONTH_YEAR_SLASHES,
	YEAR_MONTH_DAY_DOTS,
	MONTH_DAY_YEAR_DOTS,
	DAY_MONTH_YEAR_DOTS
}

enum lexicon_datetime_seperator {
		DASHES,
		DOTS,
		SLASHES,
		SPACES,
		CUSTOM_SYMBOL
}
enum lexicon_length {
	SHORT,
	MEDIUM,
	LONG,
	FULL
}